spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: karanhpadhiyar12345@gmail.com
    password: fdpp tchd fmcf odag
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true